config/routes.rb
Rails.application.routes.draw do
  resources :articles
  root 'pages#home' #home action in pages controller
  #get request to the about page from the about action in the page controller
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: {minimum: 6, maximum: 100}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles
  validates :username, presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,
            uniqueness: { case_sensitive: false },
            length: { maximum: 105 },
            format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles or /articles.json
  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)
    @article.user = User.first
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description)
    end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true
class PagesController < ApplicationController
  def home; end

  def about; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'Your account information was successfully updated'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome to the Alpha Blog #{@user.username}! You have successfully signed up."
      redirect_to articles_path
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = { size: 80 })
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block mt-3")
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="container">
  <% @articles.each do |article| %>
    <div class="row justify-content-md-center">
      <div class="col-6 mt-4"> <!-- Bootstrap operates on a 12 column grid system -->
        <div class="card text-center shadow mb-5 bg-white rounded border-dark">
          <div class="card-header fst-italic">
            <% if article.user %>
            by <%= link_to article.user.username, user_path(article.user) %>
            <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article_path(article), class:"text-dark bg-white"%></h5>
            <p class="card-text"><%= truncate(article.description, length:50) %></p>
            <a href="#"><%= link_to 'View', article_path(article), class:"btn btn-outline-info" %></a>
            <a href="#"><%= link_to 'Edit', edit_article_path(article),
                                    class:"btn btn-outline-dark"%></a>
            <a href="#"><%= link_to 'Delete', article, method: :delete, class:"btn btn-outline-danger",
                                    data: { confirm: 'Are you sure?' }%></a>
          </div>
          <div class="card-footer text-muted color-pink">
            <small> Created <%= time_ago_in_words(article.created_at) %> ago,
              edited <%= time_ago_in_words(article.updated_at) %> ago </small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<div class="container">
  <div class="row justify-content-left">
    <div class="col-10 mt-2"  id="submit-form">
      <%= render 'shared/errors', obj: @article %>
      <%= form_with(model: article, class: "shadow p-3 mb-3 rounded", local: true) do |form| %>
        <div class="form-group row mt-3" id="form-labels">
          <%= form.label :title, class: "col-2 col-form-label text-muted" %>
          <div class="col-10">
            <%= form.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
          </div>
        </div>

        <div class="form-group row mt-3" id="form-labels">
          <%= form.label :description, class: "col-2 col-form-label text-muted" %>
          <div class="col-10">
            <%= form.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
          </div>
        </div>

        <div class="form-group row justify-content-center" id="update-button" >
          <%= form.submit class: "mt-4 col-3 btn btn-outline-dark btn-lg" %>
        </div>
      <% end %>
    </div>
    <div id="back-button">
      <%= link_to '[ Back ]', articles_path%>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h2 class="text-center mt-4">Edit Article</h2>
<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<h2 class="text-center mt-4">Articles List</h2>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render 'article' %>

<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<h2 class="text-center mt-4">Create a New Article</h2>
<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<%= link_to gravatar_for(@article.user, size: 60), user_path(@article.user) %>
<h2 class="text-center mt-4"><%= @article.title %></h2>

<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-6 mt-4"> <!-- Bootstrap operates on a 12 column grid system -->
      <div class="card text-center shadow mb-5 bg-white rounded border-dark">
        <div class="card-header fst-italic">
          by <%= @article.user.username if @article.user %>
        </div>
        <div class="card-body">
          <div class="card-text text-left"><%= simple_format(@article.description) %></div>
          <a href="#"><%= link_to 'Edit', edit_article_path(@article),
                                  class:"btn btn-outline-dark"%></a>
          <a href="#"><%= link_to 'Delete', @article, method: :delete, class:"btn btn-outline-danger",
                                  data: { confirm: 'Are you sure?' }%></a>
        </div>
        <div class="card-footer text-muted color-pink">
          <small> Created <%= time_ago_in_words(@article.created_at) %> ago,
            edited <%= time_ago_in_words(@article.updated_at) %> ago </small>
        </div>
      </div>
    </div>
  </div>
  <div id="back-button">
    <a href=#><%= link_to '[ Back ]', articles_path, class:"link-dark" %></a>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="mt-auto py-3 bg-dark">
  <div class = "container text-center">
    <span class = "text-muted">Copyright &copy; Alpha Blog</span>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name,msg| %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= msg %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "ALPHA BLOG", root_path, class:"navbar-brand", id:"logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "About", about_path, class:"nav-link active"%>
        </li>
        <li class="nav-item">
          <%= link_to "Articles", articles_path, class:"nav-link active"%>
        </li>
        <li class="nav-item">
          <%= link_to "Users", users_path, class:"nav-link active"%>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">+</a>
          <ul class="dropdown-menu">
            <li><%= link_to "Create New Article", new_article_path, class:"dropdown-item"%></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to "Create New Profile", signup_path, class:"dropdown-item"%></li>
          </ul>
        </li>
      </ul>
      </ul>
      <li class="nav-item">
        <%= link_to "Sign Up", signup_path, class:"btn btn-outline-light text-light bg-black"%>
      </li>
      </ul>


      <!--        <li class="nav-item dropdown">-->
      <!--          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Users</a>-->
      <!--          <ul class="dropdown-menu">-->
      <!--            <li><%#= link_to "Create New Profile", signup_path, class:"dropdown-item"%></li>-->
      <!--            <li><hr class="dropdown-divider"></li>-->
      <!--            <li><%#= link_to "Alpha Bloggers", users_path, class:"dropdown-item"%></li>-->
      <!--          </ul>-->
      <!--        </li>-->
      <!--        <li class="nav-item dropdown">-->
      <!--          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Articles</a>-->
      <!--          <ul class="dropdown-menu">-->
      <!--            <li><%#= link_to "View Articles", articles_path, class:"dropdown-item"%></li>-->
      <!--            <li><hr class="dropdown-divider"></li>-->
      <!--            <li><%#= link_to "Create New Article", new_article_path, class:"dropdown-item"%></li>-->
      <!--          </ul>-->
      <!--        </li>-->

      <!--      <form class="d-flex">-->
      <!--        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">-->
      <!--        <button class="btn btn-outline-light" type="submit">Search</button>-->
      <!--      </form>-->
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Practice</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="d-flex flex-column">
<%= render 'layouts/navigation' %>
<div id="page-content">
  <%= render 'layouts/messages' %>
  <%= yield %>
</div>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/about.html.erb
<div class="container" id="about-container">
  <div class="card text-center text-white" id="about-body" style="width: 80rem; height: 25rem;">
    <div class="card-body" id="about-card-body">
      <h5 class="display-5">The About Page</h5>
      <hr class="my-4">
      <p class="lead">Welcome to the Alpha Blog! This blog was created following the tutorials on Mashrur Hossain's
        "The Complete Ruby on Rails Developer Course", and utilizes Ruby on Rails, Bootstrap, HTML, and CSS! On this
        blog you can create new articles, view the articles you have created, update articles, and even delete
        articles if desired. Hope you enjoy this blog with a little freestyle.</p>
      </div>
    </div>
  <div id="home-button">
    <a href="#"><%= link_to "Home", root_path, class:"btn btn-light mt-3"%></a>
  </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container" id="home-container">
  <div class="card text-center text-white" id="home-body" style="width: 80rem; height: 25rem;">
    <div class="card-body" id="home-card-body">
      <h3 class="display-4">Welcome to Sara Ibrahim's Alpha Blog!</h3>
      <hr class="my-4">
      <p class="lead">A place to create, share, and browse articles.</p>
      <a href="#"><%= link_to "Browse Articles", articles_path, class:"btn btn-light mt-3"%></a>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show mt-2" role="alert">
    <h5 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved:</h5>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-left">
    <div class="col-8 mt-4"  id="user-form">
      <%= render 'shared/errors', obj: @user %>
      <%= form_with(model: @user, class: "shadow p-3 mb-3 rounded", local: true) do |form| %>
        <div class="form-group row mt-3" id="form-labels">
          <%= form.label :username, class: "col-2 col-form-label text-muted" %>
          <div class="col-10">
            <%= form.text_field :username, class: "form-control shadow rounded", placeholder: "Username" %>
          </div>
        </div>

        <div class="form-group row mt-3" id="form-labels">
          <%= form.label :email, class: "col-2 col-form-label text-muted" %>
          <div class="col-10">
            <%= form.email_field :email, rows: 10, class: "form-control shadow rounded", placeholder: "Email" %>
          </div>
        </div>

        <div class="form-group row mt-3" id="form-labels">
          <%= form.label :password, class: "col-2 col-form-label text-muted" %>
          <div class="col-10">
            <%= form.password_field :password, rows: 10, class: "form-control shadow rounded", placeholder: "Password" %>
          </div>
        </div>

        <div class="form-group row justify-content-center" id="signup-button" >
          <%= form.submit(@user.new_record? ? "Sign up" : "Update account",
                          class: "mt-4 col-3 btn btn-outline-dark btn-lg") %>
        </div>
      <% end %>
    </div>
    <div id="back-button">
      <%= link_to '[ Back ]', users_path %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h2 class="text-center mt-4">Edit profile</h2>
<%= render 'form'%>

app/views/users/index.html.erb
<h2 class="text-center mt-4">✨ Alpha Bloggers ✨</h2>

<div class="flickr_pagination">
  <%= will_paginate @users, :container => false %>
</div>

<div class="container">
  <% @users.each do |user| %>
    <div class="row justify-content-md-center">
      <div class="col-6 mt-4"> <!-- Bootstrap operates on a 12 column grid system -->
        <div class="card text-center shadow mb-5 bg-white rounded border-dark">
          <div class="card-header fw-bold">
            <%= user.username %>
          </div>
          <div class="card-body">
            <h5 class="card-title">
              <%= link_to gravatar_for(user, size: 100), user %>
            </h5>
            <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
            <a href="#"><%= link_to 'View Profile', user, class:"btn btn-outline-info" %></a>
            <a href="#"><%= link_to 'Edit Profile', edit_user_path(user),
                                    class:"btn btn-outline-dark"%></a>
          </div>
          <div class="card-footer text-muted color-pink">
            <small> Joined <%= time_ago_in_words(user.created_at) %> ago </small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="flickr_pagination mb-4">
  <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h2 class="text-center mt-4">Sign up for Alpha Blog</h2>
<%= render 'form'%>

app/views/users/show.html.erb
<%= gravatar_for @user, size: 170 %>

<h2 class="text-center mt-3"><%= @user.username %>'s Profile</h2>

<div class="text-center mt-4">
  <%= link_to "Edit Profile", edit_user_path(@user), class: "btn btn-outline-dark" %>
</div>

<%= render 'articles/article' %>

<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>